### ISSUE TITLE
Stock Price Prediction Using a Graph-Mamba Approach

### ISSUE THREAD

**Issue by Ali-Meh619** [jwwthu/DL4Stock#2]
Hello @jwwthu ,

I and my colleagues recently submitted a paper with the title "Mamba Meets Financial Markets: A Graph-Mamba Approach for Stock Price Prediction". Here is the link to the arxiv version:
https://arxiv.org/abs/2410.03707

I would appreciate it if you can put that on your github account "DL4Stock".
Thank you in advance for your consideration.

All the best,
Ali Mehrabian

**Comment by jwwthu** [comment]
Dear Ali, let me update it after it is accepted and published. Sorry for the delay.

**Comment by Ali-Meh619** [comment]
Hello,
I hope you are doing well.
I just want to let you know that our proposed SAMBA model for stock price prediction is accepted for publication in IEEE ICASSP.
Here is the Github:
https://github.com/Ali-Meh619/SAMBA

[https://opengraph.githubassets.com/644ee69c8048d5528e0bce547d04835742c797ba4a91ad2f289eb85ead980528/Ali-Meh619/SAMBA]<https://github.com/Ali-Meh619/SAMBA>
Ali-Meh619/SAMBA - GitHub<https://github.com/Ali-Meh619/SAMBA>
Contribute to Ali-Meh619/SAMBA development by creating an account on GitHub.
github.com

I would appreciate it if you can include that in your github page.
Best,
Ali

________________________________
